---
model:
  cnn_backbone: "resnet18"
  image_size: 128
  max_seq_length: 20
  num_decoder_layers: 1
  n_head: 1
  d_model: 512
  fc_dim: 1024
  dropout: 0.1

learner: 
  lr: 0.0003
  weight_decay: 0.01

callbacks:
  checkpoint:
    monitor: "val_loss"
    save_last: True
    filename: "best"
    dirpath: "models"
  early_stopping:
    monitor: "val_loss"
    patience: 5

trainer:
  epochs: 50
  gpu: 1
  fp16: True
